# Generated by Django 6.0.1 on 2026-01-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_produit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='group',
        ),
        migrations.AlterField(
            model_name='sale',
            name='type_vente',
            field=models.CharField(choices=[('DETAIL', 'Détail (Kg)'), ('CARTON', 'Carton')], max_length=10),
        ),
        migrations.DeleteModel(
            name='SaleGroup',
        ),
    ]
