# Generated by Django 6.0.1 on 2026-01-15 16:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_produit', '0002_remove_sale_group_alter_sale_type_vente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carton',
            name='remaining_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
