# Generated by Django 6.0.1 on 2026-01-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_produit', '0003_alter_carton_remaining_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carton',
            name='initial_weight',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carton',
            name='remaining_weight',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
