# Generated by Django 6.0.1 on 2026-01-15 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_produit', '0004_alter_carton_initial_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vente', models.CharField(choices=[('DETAIL', 'Détail (Kg)'), ('CARTON', 'Carton entier')], max_length=10)),
                ('poids_vendu', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_produit.carton')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_produit.produit')),
            ],
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
